"""empty message

Revision ID: 5e4a6d51c939
Revises: 
Create Date: 2022-01-19 18:33:43.991969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4a6d51c939'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('endereco', sa.String(length=70), nullable=True),
    sa.Column('numero', sa.String(length=5), nullable=True),
    sa.Column('complemento', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('carrinho_de_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('quantidade_de_itens', sa.Integer(), nullable=True),
    sa.Column('valor', sa.String(length=15), nullable=False),
    sa.Column('valor_pos_desconto', sa.String(length=15), nullable=True),
    sa.Column('data_de_adicao_ultimo_item', sa.Time(), nullable=True),
    sa.Column('quantidade_maxima', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('modelo', sa.String(length=20), nullable=False),
    sa.Column('cor', sa.String(length=15), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('linha', sa.String(length=20), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho_de_compras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('porcentagem', sa.Boolean(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('valor_minimo', sa.Integer(), nullable=True),
    sa.Column('valor_maximo', sa.Integer(), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho_de_compras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('id')
    )
    op.create_table('moto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('modelo', sa.String(length=15), nullable=True),
    sa.Column('cor', sa.String(length=15), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('linha', sa.String(length=15), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho_de_compras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moto')
    op.drop_table('cupom')
    op.drop_table('carro')
    op.drop_table('carrinho_de_compras')
    op.drop_table('user')
    # ### end Alembic commands ###
